groups:
  - name: fulsk-critical
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is above 85% on {{ $labels.instance }}"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is above 80% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) * 100 < 10
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is below 10% on {{ $labels.instance }}"

  - name: fulsk-application
    rules:
      - alert: BackendDown
        expr: up{job="fulsk-backend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Fulsk backend is down"
          description: "The Fulsk backend application is not responding"

      - alert: FrontendDown
        expr: up{job="fulsk-frontend"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Fulsk frontend is down"
          description: "The Fulsk frontend application is not responding"

      - alert: DatabaseDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL database is down"
          description: "The PostgreSQL database is not responding"

      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "The Redis cache is not responding"

      - alert: MqttDown
        expr: up{job="mqtt"} == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "MQTT broker is down"
          description: "The MQTT broker is not responding"

      - alert: HighResponseTime
        expr: http_request_duration_seconds{quantile="0.95"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.instance }}"
          description: "95th percentile response time is above 2 seconds"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "Error rate is above 10% for 5 minutes"

  - name: fulsk-database
    rules:
      - alert: DatabaseConnectionsHigh
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "PostgreSQL connections are above 80% of max_connections"

      - alert: DatabaseSlowQueries
        expr: pg_stat_activity_max_tx_duration > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "Database queries taking longer than 5 minutes detected"

      - alert: DatabaseReplicationLag
        expr: pg_replication_lag_seconds > 30
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Database replication lag"
          description: "PostgreSQL replication lag is above 30 seconds"

  - name: fulsk-solar-monitoring
    rules:
      - alert: InverterOffline
        expr: solar_inverter_status == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Solar inverter {{ $labels.inverter_id }} is offline"
          description: "Solar inverter {{ $labels.inverter_id }} has been offline for more than 5 minutes"

      - alert: LowPowerGeneration
        expr: solar_power_generation_watts < 100
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low power generation from inverter {{ $labels.inverter_id }}"
          description: "Power generation is below 100W for more than 15 minutes during daylight hours"

      - alert: InverterError
        expr: solar_inverter_error_count > 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Solar inverter {{ $labels.inverter_id }} reporting errors"
          description: "Inverter {{ $labels.inverter_id }} has reported {{ $value }} errors"

      - alert: HighInverterTemperature
        expr: solar_inverter_temperature_celsius > 65
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High temperature on inverter {{ $labels.inverter_id }}"
          description: "Inverter temperature is {{ $value }}°C, above safe operating threshold"