global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'fulsk-monitor'
    project: 'fulsk-solar-monitoring'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s
    metrics_path: '/metrics'

  # Backend application metrics
  - job_name: 'fulsk-backend'
    static_configs:
      - targets: ['backend:3001']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Frontend nginx metrics
  - job_name: 'fulsk-frontend'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 10s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # MQTT metrics
  - job_name: 'mqtt'
    static_configs:
      - targets: ['mqtt-exporter:9234']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # Blackbox exporter for health checks
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://frontend:3000/health
        - http://backend:3001/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Solar inverter metrics (custom exporter)
  - job_name: 'solar-inverters'
    static_configs:
      - targets: ['inverter-exporter:9876']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 30s